
image:
  repository: otel/opentelemetry-collector-k8s

mode: daemonset

presets:
  kubernetesAttributes:
    enabled: true

config:
  exporters:
    otlphttp:
      endpoint: http://otel-demo.testing.svc:4318
  receivers:
    jaeger: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    prometheus: null
    zipkin:
      endpoint: null
  service:
    pipelines:
      logs:
        exporters:
          - otlphttp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics:
        exporters:
          - otlphttp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      traces:
        exporters:
          - otlphttp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp

service:
  enabled: true
  type: ClusterIP
  annotations: {}

useGOMEMLIMIT: true

resources:
  limits:
    cpu: 250m
    memory: 512Mi
