#
# kubectl port-forward services/otel-demo 3000:3000 4317:4317 4318:4318 -n opentelemetry
#
apiVersion: v1
kind: Pod
metadata:
  name: otel-pod
  namespace: opentelemetry
  labels:
    app.kubernetes.io/name: otel
spec:
  containers:
    - name: otel-lgtm
      image: grafana/otel-lgtm
      ports:
        - containerPort: 3000
        - containerPort: 4317
        - containerPort: 4318
      env:
        - name: OTEL_METRIC_EXPORT_INTERVAL
          value: "500"
---
apiVersion: v1
kind: Service
metadata:
  name: otel-demo
  namespace: opentelemetry
spec:
  selector:
    app.kubernetes.io/name: otel
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: http
      protocol: TCP
      port: 4318
      targetPort: 4318
