apiVersion: v1
kind: Pod
metadata:
  name: telemetrygen-metrics
  namespace: testing
spec:
  containers:
    - image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
      name: telemetrygen
      command:
        - /telemetrygen
        - metrics
        - --otlp-insecure
        - --otlp-endpoint=opentelemetry-collector.opentelemetry.svc:4317
        - --duration=600s
        - --rate=1
#        - --otlp-attributes=k8s.pod.name="telemetrygen-metrics"
---
apiVersion: v1
kind: Pod
metadata:
  name: telemetrygen-logs
  namespace: testing
spec:
  containers:
    - image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
      name: telemetrygen
      command:
        - /telemetrygen
        - logs
        - --otlp-insecure
        - --otlp-endpoint=opentelemetry-collector.opentelemetry.svc:4317
        - --duration=600s
        - --rate=1
#        - --otlp-attributes=k8s.pod.name="telemetrygen-logs"
---
apiVersion: v1
kind: Pod
metadata:
  name: telemetrygen-traces
  namespace: testing
spec:
  containers:
    - image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
      name: telemetrygen
      command:
        - /telemetrygen
        - traces
        - --otlp-insecure
        - --otlp-endpoint=opentelemetry-collector.opentelemetry.svc:4317
        - --duration=600s
        - --rate=1
#        - --otlp-attributes=k8s.pod.name="telemetrygen-traces"
